pr1_job:
    path:     /
    defaults: { _controller: "Pr1JobeetBundle:Job:index" }

pr1_job_show:
    path:    /{company}/{location}/{id}/{position}
    defaults: { _controller: "Pr1JobeetBundle:Job:show" }
    requirements:
        id: \d+
    methods:  GET

pr1_job_preview:
    path:    /{company}/{location}/{token}/{position}
    defaults: { _controller: "Pr1JobeetBundle:Job:preview" }
    requirements:
        token: \w+

pr1_job_new:
    path:     /new
    defaults: { _controller: "Pr1JobeetBundle:Job:new" }

pr1_job_create:
    path:     /create
    defaults: { _controller: "Pr1JobeetBundle:Job:create" }
    methods:  POST

pr1_job_edit:
    path:     /{token}/edit
    defaults: { _controller: "Pr1JobeetBundle:Job:edit" }

pr1_job_update:
    path:     /{token}/update
    defaults: { _controller: "Pr1JobeetBundle:Job:update" }
    methods:  [POST, PUT]

pr1_job_delete:
    path:     /token}/delete
    defaults: { _controller: "Pr1JobeetBundle:Job:delete" }
    methods:  [POST, DELETE]

pr1_job_publish:
    path:      /{token}/publish
    defaults: { _controller: "Pr1JobeetBundle:Job:publish" }
    methods:  POST
