<?php

namespace Pr1\JobeetBundle\Entity;

/**
 * AffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateRepository extends \Doctrine\ORM\EntityRepository
{
}
