Pr1\JobeetBundle\Entity\Affiliate:
    type: entity
    table: affiliate
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        token:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        isActive:
            type: boolean
            nullable: true
            comment: ''
            column: is_active
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
    manyToMany:
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: affiliate
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
